# Generated by Django 5.1.2 on 2024-10-15 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuários no Chat')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['dataCriacao'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(default=' ', max_length=2800, verbose_name='Conteúdo da Mensagem')),
                ('dataEnvio', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Envio')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webchat.chat', verbose_name='Chat')),
                ('quemEnviou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quemEnviou', to=settings.AUTH_USER_MODEL, verbose_name='Quem enviou')),
                ('quemLeu', models.ManyToManyField(related_name='quemLeu', to=settings.AUTH_USER_MODEL, verbose_name='Usuários que leram')),
                ('quemRecebeu', models.ManyToManyField(related_name='quemRecebeu', to=settings.AUTH_USER_MODEL, verbose_name='Usuários que receberam')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['dataEnvio', 'chat'],
            },
        ),
    ]
