# Generated by Django 5.1.2 on 2024-10-30 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessages',
            options={'ordering': ['chat', 'dataEnvio'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensagem', models.TextField(default=' ', max_length=300, verbose_name='Conteúdo da Mensagem de solicitação')),
                ('aceito', models.BooleanField(default=False, verbose_name='Aceitou a solicitação?')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webchat.chat', verbose_name='Chat')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_solicitante', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que solicitou o Chat')),
                ('usuarioDestino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_alvo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário alvo do Chat')),
            ],
            options={
                'verbose_name': 'Solicitação de Chat',
                'verbose_name_plural': 'Solicitações de Chats',
                'ordering': ['dataCriacao'],
            },
        ),
    ]
